[app]
wifi_ssid = "test-ssid"
wifi_password = "test-pass"
wifi_username = "test-user" # set to "" for WPA Personal
sip_registrar = "sip:registrar@example.com"
sip_contact = "sip:user@example.com"
sip_username = "user"
sip_password = "pass"
sip_target = "sip:100@example.com"
ring_timeout = 15
task_stats = true
