[app]
wifi_ssid = "test-ssid"
wifi_password = "test-pass"
sip_registrar = "sip:registrar@example.com"
sip_contact = "sip:user@example.com"
sip_username = "user"
sip_password = "pass"
sip_target = "sip:100@example.com"
